[dev]
  functions = "./netlify/functions"
  functionsPort = 4000

[functions]
  directory = "./netlify/functions"
  included_files = ["fonts/**"]

[build]
  functions = "./netlify/dist"

[[redirects]]
/generate /.netlify/functions/meme 200